# Generated by Django 5.2.7 on 2025-11-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='filmesvistos',
            new_name='filmes_vistos',
        ),
    ]
